import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'vi' | 'zh' | 'ja';
export type Theme = 'dark' | 'light';
export type AccentColor = '#f97316' | '#3b82f6' | '#10b981' | '#8b5cf6' | '#ef4444';

interface SettingsContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    theme: Theme;
    setTheme: (theme: Theme) => void;
    accentColor: AccentColor;
    setAccentColor: (color: AccentColor) => void;
    t: (key: string, replacements?: Record<string, string | number>) => string;
}

const SETTINGS_STORAGE_KEY = 'flix_settings';

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.home': 'Home',
        'nav.library': 'Library',
        'nav.search': 'Search',
        'nav.downloads': 'Downloads',
        'nav.history': 'History',
        'nav.settings': 'Settings',
        'nav.manga': 'Manga',
        'nav.novel': 'Novel',
        'nav.movie': 'Movie',
        'settings.account': 'Account',
        'settings.logged_in': 'Logged in',
        'settings.edit_profile': 'Edit Profile',
        'settings.appearance': 'Appearance',
        'settings.theme': 'Theme',
        'settings.theme.dark': 'Dark',
        'settings.theme.light': 'Light',
        'settings.accent_color': 'Accent Color',
        'settings.language': 'Language',
        'settings.about': 'About',
        'settings.version': 'Version',
        'settings.logout': 'Logout',
        'settings.unlock.placeholder': 'Enter passcode...',
        'settings.unlock.verify': 'Verify',
        'settings.unlock.success': 'Source unlocked!',
        'settings.unlock.fail': 'Invalid key',
        'search.placeholder': 'Search comics...',
        'search.type_more': 'Type at least 3 characters...',
        'search.no_results': 'No results found for "{query}"',
        'search.error': 'Error searching.',
        'search.genres': 'Genres',
        'search.nhentai.tags': 'Tags',
        'search.nhentai.artists': 'Artists',
        'search.nhentai.characters': 'Characters',
        'search.nhentai.parodies': 'Parodies',
        'search.nhentai.groups': 'Groups',
        'source.latest': 'Last Updates',
        'source.popular': 'Popular',
        'source.popular_current': 'Current',
        'source.popular_today': 'Today',
        'source.popular_week': 'This Week',
        'source.popular_month': 'This Month',
        'source.popular_all': 'All Time',
        'source.completed': 'Completed',
        'source.unsupported': 'Source "{source}" not supported currently.',
        'source.error': 'Error loading data.',
        'source.list_title': '{source} List',

        'profile.edit_title': 'Edit Profile',
        'profile.save': 'Save',
        'profile.display_name': 'Display Name',
        'profile.bio': 'Bio',
        'profile.bio_placeholder': 'Tell us about yourself...',
        'profile.upload_success': 'Image uploaded successfully!',
        'profile.upload_failed': 'Failed to upload image.',
        'profile.save_success': 'Profile successfully updated!',
        'profile.save_failed': 'Failed to save profile.',
        'profile.crop_title': 'Edit Image',
        'profile.crop_zoom_out': 'Zoom out',
        'profile.crop_zoom_in': 'Zoom in',
        'profile.crop_done': 'Done',
        'profile.no_frame': 'NONE',
        'profile.no_cover': 'NONE',

        'downloads.clear_all': 'Clear All',
        'downloads.pause_all': 'Pause All',
        'downloads.resume': 'Resume ({count})',
        'downloads.start': 'Start ({count})',
        'downloads.no_downloads': 'No downloads in queue.',
        'downloads.queue': 'Queue',
        'downloads.completed': 'Completed',
        'downloads.clear_history': 'Clear History',
        'comic.chapters': 'Chapters',
        'comic.total': '{count} total',
        'comic.download_all': 'Download All (ZIP)',
        'comic.queue_all': 'Queue All',
        'comic.read': 'Read',
        'chapters.downloading': 'Downloading...',
        'chapters.completed': 'Done',
        'chapters.pending': 'Pending',
        'chapters.paused': 'Paused',
        'chapters.failed': 'Failed',

        // Reader Settings
        'reader.settings.mode': 'Reading Mode',
        'reader.settings.general': 'General',
        'reader.settings.filters': 'Custom Filters',
        'reader.settings.reading_mode': 'Reading Mode',
        'reader.mode.default': 'Default',
        'reader.mode.paged': 'Paged (L to R)',
        'reader.mode.webtoon': 'Vertical Scroll',
        'reader.settings.tap_zone': 'Tap Zone',
        'reader.tap.default': 'Default',
        'reader.tap.l_shape': 'L-Shape',
        'reader.tap.kindle': 'Kindle-like',
        'reader.tap.off': 'Off',
        'reader.settings.invert_tap': 'Invert Tap Zones',
        'reader.invert.none': 'None',
        'reader.invert.horizontal': 'Horizontal',
        'reader.invert.vertical': 'Vertical',
        'reader.invert.both': 'Both',
        'reader.settings.side_padding': 'Side Padding',
        'reader.settings.auto_scroll': 'Auto-scroll Speed',
        'reader.settings.auto_scroll_level': 'Level {level}',
        'reader.settings.double_tap_zoom': 'Double tap to zoom',
        'reader.settings.bg_color': 'Background Color',
        'reader.bg.black': 'Black',
        'reader.bg.gray': 'Gray',
        'reader.bg.white': 'White',
        'reader.settings.show_page': 'Show Page Number',
        'reader.settings.fullscreen': 'Fullscreen',
        'reader.settings.custom_brightness': 'Custom Brightness',
        'reader.settings.grayscale': 'Grayscale',
        'reader.settings.invert_colors': 'Invert Colors',
        'reader.settings.crop_borders': 'Crop Borders',
        'reader.settings.split_double_pages': 'Split Double Pages',

        // Misc
        'reader.chapter': 'Chapter {number}',
        'comic.continue_reading': 'Continue Reading',
        'comic.start_reading': 'Start Reading',
        'comic.latest_chapter': 'Latest Chapter',
        'comic.author': 'Author',
        'comic.status': 'Status',
        'comic.status.ongoing': 'Ongoing',
        'comic.status.completed': 'Completed',
        // Comic Detail Modals
        'comic.filter': 'Filter',
        'comic.sort': 'Sort',
        'comic.display': 'Display',
        'comic.filter.downloaded': 'Downloaded',
        'comic.filter.unread': 'Unread',
        'comic.filter.bookmarked': 'Bookmarked',
        'comic.sort.source': 'By Source Name / Alphabetical',
        'comic.sort.chapter': 'By Chapter Number',
        'comic.sort.date': 'By Upload Date (API not supported)',
        'comic.display.source': 'Source Title',
        'comic.display.chapter': 'Chapter Number',
        'comic.added_queue': 'Added all to queue',
        'comic.added_zip_queue': 'Added entire comic (ZIP) to download queue!',
        'comic.added_chapter': 'Added Chapter {number}',
        'comic.added_chapter_queue': 'Added Chapter {number} to download progress',
        'comic.no_chapters': 'No chapters',
        'comic.queue_count': 'Scheduled {count} chapters for download',
        'comic.mark_read': 'Mark Read',
        'comic.mark_unread': 'Mark Unread',
        'comic.mark_read_down': 'Mark Read Down',
        'comic.bookmark': 'Bookmark',
        'comic.add_queue': 'Add to Queue',
        'comic.download_now': 'Download Now',

        // Home & Library
        'home.browse': 'Browse Sources',
        'home.latest': 'LATEST',
        'home.coming_soon': 'Coming soon in future updates.',
        'library.title': 'Library',
        'library.empty': 'Your library is empty.',
        'library.browse': 'Browse Comics',
        'library.failed': 'Failed to load library.',

        //History
        'history.empty': 'No reading history yet.',
        'history.failed': 'Failed to load history.',
        'history.img_not_found': 'No Img',
        'player.speed': 'Speed',
        'player.subtitles': 'Subtitles',
        'player.episodes': 'Episodes',
        'player.next_episode': 'Next Ep',
        'player.skip_intro': 'Skip Intro',
        'player.now_playing': 'Now Playing',
        'player.source_language': 'Source & Language',
        'kkphim.filter.release_year': 'Release Year',
        'kkphim.filter.all_years': 'All Years',
        'kkphim.type.phimbo': 'Series',
        'kkphim.type.phimle': 'Movie',

        'mtc.tabs.latest': 'Latest',
        'mtc.tabs.hot': 'Hot',
        'mtc.tabs.completed': 'Completed',
        'mtc.tabs.curated': 'Curated',
        'mtc.tabs.random': 'Random',
        'mtc.tabs.popular': 'Popular',
        'mtc.sort.viewday': 'Current',
        'mtc.sort.viewweek': 'This Week',
        'mtc.sort.view': 'All Time',
        'mtc.sort.like': 'Likes',
        'mtc.sort.following': 'Following',
        'mtc.sort.bookmarked': 'Bookmarked',
        'kkphim.filter.all': 'All',
        'kkphim.filter.all_genres': 'All Genres',
        'kkphim.filter.all_countries': 'All Countries',
        'kkphim.filter.type': 'Type',
        'kkphim.filter.sort': 'Sort By',
        'kkphim.filter.country': 'Country',
        'kkphim.type.series': 'Series',
        'kkphim.type.single': 'Movie',
        'kkphim.type.hoathinh': 'Animation',
        'kkphim.type.tvshows': 'TV Shows',
        'kkphim.sort.update': 'Recently Updated',
        'kkphim.sort.year': 'Release Year',
        'kkphim.sort.new': 'Newly Added',
        'movie.watch_now': 'Watch Now',
        'movie.watch_trailer': 'Watch Trailer',
        'movie.synopsis': 'Synopsis',
        'movie.episode_list': 'Episode List',
        'kkphim.category.hanh-dong': 'Action',
        'kkphim.category.co-trang': 'Historical',
        'kkphim.category.chien-tranh': 'War',
        'kkphim.category.vien-tuong': 'Sci-Fi',
        'kkphim.category.kinh-di': 'Horror',
        'kkphim.category.tai-lieu': 'Documentary',
        'kkphim.category.bi-an': 'Mystery',
        'kkphim.category.phim-18': '18+',
        'kkphim.category.tinh-cam': 'Romance',
        'kkphim.category.tam-ly': 'Drama',
        'kkphim.category.the-thao': 'Sports',
        'kkphim.category.phieu-luu': 'Adventure',
        'kkphim.category.am-nhac': 'Music',
        'kkphim.category.gia-dinh': 'Family',
        'kkphim.category.hoc-duong': 'School',
        'kkphim.category.hai-huoc': 'Comedy',
        'kkphim.category.hinh-su': 'Crime',
        'kkphim.category.vo-thuat': 'Martial Arts',
        'kkphim.category.khoa-hoc': 'Science',
        'kkphim.category.than-thoai': 'Mythology',
        'kkphim.category.chinh-kich': 'Drama',
        'kkphim.category.kinh-dien': 'Classic',
        'kkphim.category.phim-ngan': 'Short Film',
        'kkphim.country.trung-quoc': 'China',
        'kkphim.country.thai-lan': 'Thailand',
        'kkphim.country.hong-kong': 'Hong Kong',
        'kkphim.country.phap': 'France',
        'kkphim.country.duc': 'Germany',
        'kkphim.country.ha-lan': 'Netherlands',
        'kkphim.country.mexico': 'Mexico',
        'kkphim.country.thuy-dien': 'Sweden',
        'kkphim.country.philippines': 'Philippines',
        'kkphim.country.dan-mach': 'Denmark',
        'kkphim.country.thuy-si': 'Switzerland',
        'kkphim.country.ukraina': 'Ukraine',
        'kkphim.country.han-quoc': 'South Korea',
        'kkphim.country.au-my': 'Europe & US',
        'kkphim.country.an-do': 'India',
        'kkphim.country.canada': 'Canada',
        'kkphim.country.tay-ban-nha': 'Spain',
        'kkphim.country.indonesia': 'Indonesia',
        'kkphim.country.ba-lan': 'Poland',
        'kkphim.country.malaysia': 'Malaysia',
        'kkphim.country.bo-dao-nha': 'Portugal',
        'kkphim.country.uae': 'UAE',
        'kkphim.country.chau-phi': 'Africa',
        'kkphim.country.a-rap-xe-ut': 'Saudi Arabia',
        'kkphim.country.nhat-ban': 'Japan',
        'kkphim.country.dai-loan': 'Taiwan',
        'kkphim.country.anh': 'UK',
        'kkphim.country.tho-nhi-ky': 'Turkey',
        'kkphim.country.nga': 'Russia',
        'kkphim.country.uc': 'Australia',
        'kkphim.country.brazil': 'Brazil',
        'kkphim.country.y': 'Italy',
        'kkphim.country.na-uy': 'Norway',
        'kkphim.country.nam-phi': 'South Africa',
        'kkphim.country.viet-nam': 'Vietnam',
        'kkphim.country.quoc-gia-khac': 'Other',
        'filter.all': 'All',
        'search.filter.category': 'Category',
        'search.filter.time': 'Time',
        'search.filter.views': 'Views',
        'search.filter.length': 'Length',
        'filter.time.1w': '1 Week',
        'filter.time.2w': '2 Weeks',
        'filter.time.1m': '1 Month',
        'filter.time.3m': '3 Months',
        'filter.time.6m': '6 Months',
        'filter.time.1y': '1 Year',
        'filter.views.1k': '> 1000',
        'filter.views.5k': '> 5000',
        'filter.views.10k': '> 10k',
        'filter.views.50k': '> 50k',
        'filter.views.100k': '> 100k',
        'filter.duration.5m': '> 5 mins',
        'filter.duration.10m': '> 10 mins',
        'filter.duration.30m': '> 30 mins',
        'filter.duration.60m': '> 60 mins',
        'thepy.category.china': 'China',
        'thepy.category.taiwan': 'Taiwan',
        'thepy.category.japan': 'Japan',
        'thepy.category.eu': 'Europe/America',
        'thepy.tab.recent': 'Latest',
        'thepy.tab.myfavs': 'Favorites',
        'thepy.tab.filters': 'Filters'

    },
    vi: {
        'nav.home': 'Trang chủ',
        'nav.library': 'Thư viện',
        'nav.search': 'Tìm kiếm',
        'nav.downloads': 'Tải xuống',
        'nav.history': 'Lịch sử',
        'nav.settings': 'Cài đặt',
        'nav.manga': 'Truyện tranh',
        'nav.novel': 'Tiểu thuyết',
        'nav.movie': 'Phim',
        'settings.account': 'Tài khoản',
        'settings.logged_in': 'Đã đăng nhập',
        'settings.edit_profile': 'Chỉnh sửa hồ sơ',
        'settings.appearance': 'Giao diện',
        'settings.theme': 'Chủ đề',
        'settings.theme.dark': 'Tối',
        'settings.theme.light': 'Sáng',
        'settings.accent_color': 'Màu nhấn',
        'settings.language': 'Ngôn ngữ',
        'settings.about': 'Thông tin',
        'settings.version': 'Phiên bản',
        'settings.logout': 'Đăng xuất',
        'settings.unlock.placeholder': 'Nhập mã bí mật...',
        'settings.unlock.verify': 'Xác thực',
        'settings.unlock.success': 'Đã mở khoá nguồn truyện!',
        'settings.unlock.fail': 'Mã không hợp lệ',
        'search.placeholder': 'Tìm kiếm truyện...',
        'search.type_more': 'Nhập ít nhất 3 ký tự...',
        'search.no_results': 'Không tìm thấy kết quả cho "{query}"',
        'search.error': 'Lỗi tìm kiếm.',
        'search.genres': 'Thể loại',
        'search.nhentai.tags': 'Thể loại',
        'search.nhentai.artists': 'Tác giả',
        'search.nhentai.characters': 'Nhân vật',
        'search.nhentai.parodies': 'Đồng nhân',
        'search.nhentai.groups': 'Nhóm',
        'source.latest': 'Mới nhất',
        'source.popular': 'Phổ biến',
        'source.popular_current': 'Hiện tại',
        'source.popular_today': 'Trong ngày',
        'source.popular_week': 'Trong tuần',
        'source.popular_month': 'Trong tháng',
        'source.popular_all': 'Toàn bộ',
        'source.completed': 'Hoàn thành',
        'source.unsupported': 'Nguồn "{source}" hiện không được hỗ trợ.',
        'source.error': 'Lỗi tải dữ liệu.',
        'source.list_title': 'Danh sách {source}',

        'profile.edit_title': 'Chỉnh sửa hồ sơ',
        'profile.save': 'Lưu',
        'profile.display_name': 'Tên hiển thị',
        'profile.bio': 'Tiểu sử',
        'profile.bio_placeholder': 'Chia sẻ điều gì đó về bạn...',
        'profile.upload_success': 'Tải ảnh thành công!',
        'profile.upload_failed': 'Tải ảnh thất bại.',
        'profile.save_success': 'Cập nhật hồ sơ thành công!',
        'profile.save_failed': 'Lưu hồ sơ thất bại.',
        'profile.crop_title': 'Chỉnh sửa ảnh',
        'profile.crop_zoom_out': 'Thu nhỏ',
        'profile.crop_zoom_in': 'Phóng to',
        'profile.crop_done': 'Xong',
        'profile.no_frame': 'KHÔNG CÓ',
        'profile.no_cover': 'KHÔNG CÓ',

        'downloads.clear_all': 'Xóa tất cả',
        'downloads.pause_all': 'Dừng tất cả',
        'downloads.resume': 'Tiếp tục ({count})',
        'downloads.start': 'Bắt đầu ({count})',
        'downloads.no_downloads': 'Không có tải xuống nào.',
        'downloads.queue': 'Hàng đợi',
        'downloads.completed': 'Đã hoàn thành',
        'downloads.clear_history': 'Xóa lịch sử',
        'comic.chapters': 'Danh sách chương',
        'comic.total': 'Tổng {count}',
        'comic.download_all': 'Tải bộ truyện (ZIP)',
        'comic.queue_all': 'Thêm tất cả vào hàng chờ',
        'comic.read': 'Đọc',
        'chapters.downloading': 'Đang tải...',
        'chapters.completed': 'Xong',
        'chapters.pending': 'Chờ tải',
        'chapters.paused': 'Đã dừng',
        'chapters.failed': 'Lỗi',

        // Reader Settings
        'reader.settings.mode': 'Kiểu đọc',
        'reader.settings.general': 'Chung',
        'reader.settings.filters': 'Bộ lọc tùy chỉnh',
        'reader.settings.reading_mode': 'Kiểu đọc',
        'reader.mode.default': 'Mặc định',
        'reader.mode.paged': 'Trang sách',
        'reader.mode.webtoon': 'Cuộn dọc',
        'reader.settings.tap_zone': 'Khu vực nhấn',
        'reader.tap.default': 'Mặc định',
        'reader.tap.l_shape': 'Dạng chữ L',
        'reader.tap.kindle': 'Dạng giống Kindle',
        'reader.tap.off': 'Tắt',
        'reader.settings.invert_tap': 'Đảo ngược khu vực nhấn',
        'reader.invert.none': 'Không',
        'reader.invert.horizontal': 'Ngang',
        'reader.invert.vertical': 'Dọc',
        'reader.invert.both': 'Cả hai',
        'reader.settings.side_padding': 'Kích cỡ hai bên',
        'reader.settings.auto_scroll': 'Tốc độ cuộn tự động',
        'reader.settings.auto_scroll_level': 'Mức {level}',
        'reader.settings.double_tap_zoom': 'Nhấn đúp để phóng to',
        'reader.settings.bg_color': 'Màu nền',
        'reader.bg.black': 'Đen',
        'reader.bg.gray': 'Xám',
        'reader.bg.white': 'Trắng',
        'reader.settings.show_page': 'Hiện số trang',
        'reader.settings.fullscreen': 'Toàn màn hình',
        'reader.settings.custom_brightness': 'Độ sáng tùy chỉnh',
        'reader.settings.grayscale': 'Ảnh đen trắng',
        'reader.settings.invert_colors': 'Đảo màu',
        'reader.settings.crop_borders': 'Cắt viền',
        'reader.settings.split_double_pages': 'Chia các trang đôi',

        // Misc
        'reader.chapter': 'Chương {number}',
        'comic.continue_reading': 'Đọc tiếp',
        'comic.start_reading': 'Bắt đầu đọc',
        'comic.latest_chapter': 'Chương mới nhất',
        'comic.author': 'Tác giả',
        'comic.status': 'Trạng thái',
        'comic.status.ongoing': 'Đang ra',
        'comic.status.completed': 'Hoàn thành',
        // Comic Detail Modals
        'comic.filter': 'Bộ lọc',
        'comic.sort': 'Sắp xếp',
        'comic.display': 'Hiển thị',
        'comic.filter.downloaded': 'Đã tải xuống',
        'comic.filter.unread': 'Chưa đọc',
        'comic.filter.bookmarked': 'Đã đánh dấu',
        'comic.sort.source': 'Theo nguồn truyện / Bảng chữ cái',
        'comic.sort.chapter': 'Theo số chương',
        'comic.sort.date': 'Bởi ngày đăng (API không hỗ trợ)',
        'comic.display.source': 'Tiêu đề nguồn',
        'comic.display.chapter': 'Số chương',
        'comic.added_queue': 'Đã thêm toàn bộ vào hàng chờ',
        'comic.added_zip_queue': 'Đã thêm toàn bộ truyện (ZIP) vào hàng tải!',
        'comic.added_chapter': 'Đã thêm Chapter {number}',
        'comic.added_chapter_queue': 'Đã thêm Chapter {number} vào tiến trình tải',
        'comic.no_chapters': 'Chưa có chương',
        'comic.queue_count': 'Đã xếp lịch tải {count} chapter',
        'comic.mark_read': 'Đã đọc',
        'comic.mark_unread': 'Chưa đọc',
        'comic.mark_read_down': 'Đã đọc xuống',
        'comic.bookmark': 'Đánh dấu',
        'comic.add_queue': 'Thêm hàng chờ',
        'comic.download_now': 'Tải về ngay',

        // Home & Library
        'home.browse': 'Khám phá Nguồn',
        'home.latest': 'MỚI NHẤT',
        'home.coming_soon': 'Sắp ra mắt trong các bản cập nhật tới.',
        'library.title': 'Thư viện',
        'library.empty': 'Thư viện của bạn đang trống.',
        'library.browse': 'Khám phá Truyện',
        'library.failed': 'Tải thư viện thất bại.',

        //History
        'history.empty': 'Bạn chưa có lịch sử đọc truyện.',
        'history.failed': 'Tải lịch sử đọc truyện thất bại.',
        'history.img_not_found': 'Không tìm thấy ảnh',
        'player.speed': 'Tốc độ',
        'player.subtitles': 'Phụ đề',
        'player.episodes': 'Tập phim',
        'player.next_episode': 'Tập tiếp',
        'player.skip_intro': 'Bỏ qua phần giới thiệu',
        'player.now_playing': 'Đang phát',
        'player.source_language': 'Nguồn phát & Ngôn ngữ',
        'kkphim.filter.release_year': 'Năm phát hành',
        'kkphim.filter.all_years': 'Tất cả năm',
        'kkphim.type.phimbo': 'Phim Bộ',
        'kkphim.type.phimle': 'Phim Lẻ',

        'mtc.tabs.latest': 'Mới nhất',
        'mtc.tabs.hot': 'Truyện hot',
        'mtc.tabs.completed': 'Hoàn thành',
        'mtc.tabs.curated': 'Chọn lọc',
        'mtc.tabs.random': 'Ngẫu nhiên',
        'mtc.tabs.popular': 'Phổ biến',
        'mtc.sort.viewday': 'Hiện tại',
        'mtc.sort.viewweek': 'Trong tuần',
        'mtc.sort.view': 'Toàn bộ',
        'mtc.sort.like': 'Lượt thích',
        'mtc.sort.following': 'Theo dõi',
        'mtc.sort.bookmarked': 'Đánh dấu',
        'kkphim.filter.all': 'Tất cả',
        'kkphim.filter.all_genres': 'Tất cả thể loại',
        'kkphim.filter.all_countries': 'Tất cả quốc gia',
        'kkphim.filter.type': 'Loại phim',
        'kkphim.filter.sort': 'Sắp xếp theo',
        'kkphim.filter.country': 'Quốc gia',
        'kkphim.type.series': 'Phim Bộ',
        'kkphim.type.single': 'Phim Lẻ',
        'kkphim.type.hoathinh': 'Hoạt Hình',
        'kkphim.type.tvshows': 'TV Shows',
        'kkphim.sort.update': 'Mới cập nhật',
        'kkphim.sort.year': 'Năm sản xuất',
        'kkphim.sort.new': 'Mới đăng',
        'movie.watch_now': 'Xem Ngay',
        'movie.watch_trailer': 'Xem Trailer',
        'movie.synopsis': 'Nội dung phim',
        'movie.episode_list': 'Danh Sách Tập',
        'kkphim.category.hanh-dong': 'Hành Động',
        'kkphim.category.co-trang': 'Cổ Trang',
        'kkphim.category.chien-tranh': 'Chiến Tranh',
        'kkphim.category.vien-tuong': 'Viễn Tưởng',
        'kkphim.category.kinh-di': 'Kinh Dị',
        'kkphim.category.tai-lieu': 'Tài Liệu',
        'kkphim.category.bi-an': 'Bí Ẩn',
        'kkphim.category.phim-18': 'Phim 18+',
        'kkphim.category.tinh-cam': 'Tình Cảm',
        'kkphim.category.tam-ly': 'Tâm Lý',
        'kkphim.category.the-thao': 'Thể Thao',
        'kkphim.category.phieu-luu': 'Phiêu Lưu',
        'kkphim.category.am-nhac': 'Âm Nhạc',
        'kkphim.category.gia-dinh': 'Gia Đình',
        'kkphim.category.hoc-duong': 'Học Đường',
        'kkphim.category.hai-huoc': 'Hài Hước',
        'kkphim.category.hinh-su': 'Hình Sự',
        'kkphim.category.vo-thuat': 'Võ Thuật',
        'kkphim.category.khoa-hoc': 'Khoa Học',
        'kkphim.category.than-thoai': 'Thần Thoại',
        'kkphim.category.chinh-kich': 'Chính Kịch',
        'kkphim.category.kinh-dien': 'Kinh Điển',
        'kkphim.category.phim-ngan': 'Phim Ngắn',
        'kkphim.country.trung-quoc': 'Trung Quốc',
        'kkphim.country.thai-lan': 'Thái Lan',
        'kkphim.country.hong-kong': 'Hồng Kông',
        'kkphim.country.phap': 'Pháp',
        'kkphim.country.duc': 'Đức',
        'kkphim.country.ha-lan': 'Hà Lan',
        'kkphim.country.mexico': 'Mexico',
        'kkphim.country.thuy-dien': 'Thụy Điển',
        'kkphim.country.philippines': 'Philippines',
        'kkphim.country.dan-mach': 'Đan Mạch',
        'kkphim.country.thuy-si': 'Thụy Sĩ',
        'kkphim.country.ukraina': 'Ukraina',
        'kkphim.country.han-quoc': 'Hàn Quốc',
        'kkphim.country.au-my': 'Âu Mỹ',
        'kkphim.country.an-do': 'Ấn Độ',
        'kkphim.country.canada': 'Canada',
        'kkphim.country.tay-ban-nha': 'Tây Ban Nha',
        'kkphim.country.indonesia': 'Indonesia',
        'kkphim.country.ba-lan': 'Ba Lan',
        'kkphim.country.malaysia': 'Malaysia',
        'kkphim.country.bo-dao-nha': 'Bồ Đào Nha',
        'kkphim.country.uae': 'UAE',
        'kkphim.country.chau-phi': 'Châu Phi',
        'kkphim.country.a-rap-xe-ut': 'Ả Rập Xê Út',
        'kkphim.country.nhat-ban': 'Nhật Bản',
        'kkphim.country.dai-loan': 'Đài Loan',
        'kkphim.country.anh': 'Anh',
        'kkphim.country.tho-nhi-ky': 'Thổ Nhĩ Kỳ',
        'kkphim.country.nga': 'Nga',
        'kkphim.country.uc': 'Úc',
        'kkphim.country.brazil': 'Brazil',
        'kkphim.country.y': 'Ý',
        'kkphim.country.na-uy': 'Na Uy',
        'kkphim.country.nam-phi': 'Nam Phi',
        'kkphim.country.viet-nam': 'Việt Nam',
        'kkphim.country.quoc-gia-khac': 'Quốc Gia Khác',
        'filter.all': 'Tất cả',
        'search.filter.category': 'Danh mục',
        'search.filter.time': 'Thời gian',
        'search.filter.views': 'Lượt xem',
        'search.filter.length': 'Thời lượng',
        'filter.time.1w': '1 Tuần',
        'filter.time.2w': '2 Tuần',
        'filter.time.1m': '1 Tháng',
        'filter.time.3m': '3 Tháng',
        'filter.time.6m': '6 Tháng',
        'filter.time.1y': '1 Năm',
        'filter.views.1k': '> 1000',
        'filter.views.5k': '> 5000',
        'filter.views.10k': '> 10k',
        'filter.views.50k': '> 50k',
        'filter.views.100k': '> 100k',
        'filter.duration.5m': '> 5 phút',
        'filter.duration.10m': '> 10 phút',
        'filter.duration.30m': '> 30 phút',
        'filter.duration.60m': '> 60 phút',
        'thepy.category.china': 'Trung Quốc',
        'thepy.category.taiwan': 'Đài Loan',
        'thepy.category.japan': 'Nhật Bản',
        'thepy.category.eu': 'Âu Mỹ',
        'thepy.tab.recent': 'Mới nhất',
        'thepy.tab.myfavs': 'Yêu thích',
        'thepy.tab.filters': 'Bộ lọc'

    },
    zh: {
        'nav.home': '首页',
        'nav.library': '书架',
        'nav.search': '搜索',
        'nav.downloads': '下载',
        'nav.history': '历史',
        'nav.settings': '设置',
        'nav.manga': '漫画',
        'nav.novel': '小说',
        'nav.movie': '电影',
        'settings.account': '账户',
        'settings.logged_in': '已登录',
        'settings.edit_profile': '编辑资料',
        'settings.appearance': '外观',
        'settings.theme': '主题',
        'settings.theme.dark': '暗黑',
        'settings.theme.light': '明亮',
        'settings.accent_color': '强调色',
        'settings.language': '语言',
        'settings.about': '关于',
        'settings.version': '版本',
        'settings.logout': '退出登录',
        'settings.unlock.placeholder': '输入密码...',
        'settings.unlock.verify': '验证',
        'settings.unlock.success': '源码已解锁！',
        'settings.unlock.fail': '无效密钥',
        'search.placeholder': '搜索漫画...',
        'search.type_more': '输入至少3个字符...',
        'search.no_results': '未找到 "{query}" 的结果',
        'search.error': '搜索失败。',
        'search.genres': '类型',
        'search.nhentai.tags': '标签',
        'search.nhentai.artists': '作者',
        'search.nhentai.characters': '角色',
        'search.nhentai.parodies': '同人',
        'search.nhentai.groups': '团队',
        'source.latest': '最新更新',
        'source.popular': '最受欢迎',
        'source.popular_current': '当前',
        'source.popular_today': '今天',
        'source.popular_week': '本周',
        'source.popular_month': '本月',
        'source.popular_all': '全部',
        'source.completed': '已完结',
        'source.unsupported': '当前不支持源 "{source}"。',
        'source.error': '加载数据失败。',
        'source.list_title': '{source} 列表',

        'profile.edit_title': '编辑资料',
        'profile.save': '保存',
        'profile.display_name': '显示名称',
        'profile.bio': '简介',
        'profile.bio_placeholder': '介绍一下你自己...',
        'profile.upload_success': '图片上传成功！',
        'profile.upload_failed': '上传图片失败。',
        'profile.save_success': '个人资料已更新！',
        'profile.save_failed': '保存资料失败。',
        'profile.crop_title': '编辑图片',
        'profile.crop_zoom_out': '缩小',
        'profile.crop_zoom_in': '放大',
        'profile.crop_done': '完成',
        'profile.no_frame': '无',
        'profile.no_cover': '无',

        'downloads.clear_all': '全部清除',
        'downloads.pause_all': '全部暂停',
        'downloads.resume': '恢复 ({count})',
        'downloads.start': '开始 ({count})',
        'downloads.no_downloads': '队列中没有下载任务。',
        'downloads.queue': '下载队列',
        'downloads.completed': '已完成',
        'downloads.clear_history': '清除历史',

        // Comic Detail Modals
        'comic.filter': '筛选',
        'comic.sort': '排序',
        'comic.display': '显示',
        'comic.filter.downloaded': '已下载',
        'comic.filter.unread': '未读',
        'comic.filter.bookmarked': '已收藏',
        'comic.sort.source': '按源名称 / 字母顺序',
        'comic.sort.chapter': '按章节数',
        'comic.sort.date': '按更新日期 (API不支持)',
        'comic.display.source': '源标题',
        'comic.display.chapter': '章节号',
        'comic.added_queue': '已全部加入队列',
        'comic.added_zip_queue': '已将全本(ZIP)加入下载进度!',
        'comic.added_chapter': '已添加第 {number} 章',
        'comic.added_chapter_queue': '已将第 {number} 章加入下载进度',
        'comic.no_chapters': '暂无章节',
        'comic.queue_count': '已预约下载 {count} 章',
        'comic.mark_read': '标记为已读',
        'comic.mark_unread': '标记为未读',
        'comic.mark_read_down': '向下标记已读',
        'comic.bookmark': '收藏',
        'comic.add_queue': '加入队列',
        'comic.download_now': '立即下载',

        'comic.chapters': '章节',
        'comic.total': '共 {count} 章',
        'comic.download_all': '下载全部 (ZIP)',
        'comic.queue_all': '全部加入队列',
        'comic.read': '阅读',
        'chapters.downloading': '下载中...',
        'chapters.completed': '完成',
        'chapters.pending': '等待中',
        'chapters.paused': '已暂停',
        'chapters.failed': '失败',

        // Misc
        'reader.chapter': '第 {number} 話',
        'comic.continue_reading': '继续阅读',
        'comic.start_reading': '开始阅读',
        'comic.latest_chapter': '最新话',
        'comic.author': '作者',
        'comic.status': '状态',
        'comic.status.ongoing': '连载中',
        'comic.status.completed': '完结',

        // Home & Library
        'home.browse': '浏览源',
        'home.latest': '最新',
        'home.coming_soon': '即将在未来的更新中推出。',
        'library.title': '书架',
        'library.empty': '您的书架是空的。',
        'library.browse': '浏览漫画',
        'library.failed': '加载书架失败。',

        //History
        'history.empty': '您还没有阅读历史。',
        'history.failed': '加载阅读历史失败。',
        'history.img_not_found': '没有图片',
        'player.speed': '速度',
        'player.subtitles': '字幕',
        'player.episodes': '剧集',
        'player.next_episode': '下一集',
        'player.skip_intro': '跳过片头',
        'player.now_playing': '正在播放',
        'player.source_language': '来源与语言',
        'kkphim.filter.release_year': '发行年份',
        'kkphim.filter.all_years': '所有年份',
        'kkphim.type.phimbo': '剧集',
        'kkphim.type.phimle': '电影',

        'mtc.tabs.latest': '最新',
        'mtc.tabs.hot': '热门',
        'mtc.tabs.completed': '完结',
        'mtc.tabs.curated': '精选',
        'mtc.tabs.random': '随机',
        'mtc.tabs.popular': '流行',
        'mtc.sort.viewday': '当前',
        'mtc.sort.viewweek': '本周',
        'mtc.sort.view': '全部',
        'mtc.sort.like': '点赞',
        'mtc.sort.following': '关注',
        'mtc.sort.bookmarked': '收藏',
        'kkphim.filter.all': '全部',
        'kkphim.filter.all_genres': '全部类型',
        'kkphim.filter.all_countries': '全部国家',
        'kkphim.filter.type': '类型',
        'kkphim.filter.sort': '排序',
        'kkphim.filter.country': '国家',
        'kkphim.type.series': '剧集',
        'kkphim.type.single': '电影',
        'kkphim.type.hoathinh': '动画',
        'kkphim.type.tvshows': '综艺',
        'kkphim.sort.update': '最近更新',
        'kkphim.sort.year': '发行年份',
        'kkphim.sort.new': '新添加',
        'movie.watch_now': '立即观看',
        'movie.watch_trailer': '观看预告片',
        'movie.synopsis': '剧情简介',
        'movie.episode_list': '剧集列表',
        'kkphim.category.hanh-dong': '动作',
        'kkphim.category.co-trang': '古装',
        'kkphim.category.chien-tranh': '战争',
        'kkphim.category.vien-tuong': '科幻',
        'kkphim.category.kinh-di': '恐怖',
        'kkphim.category.tai-lieu': '纪录片',
        'kkphim.category.bi-an': '悬疑',
        'kkphim.category.phim-18': '18+',
        'kkphim.category.tinh-cam': '爱情',
        'kkphim.category.tam-ly': '剧情',
        'kkphim.category.the-thao': '体育',
        'kkphim.category.phieu-luu': '冒险',
        'kkphim.category.am-nhac': '音乐',
        'kkphim.category.gia-dinh': '家庭',
        'kkphim.category.hoc-duong': '校园',
        'kkphim.category.hai-huoc': '喜剧',
        'kkphim.category.hinh-su': '犯罪',
        'kkphim.category.vo-thuat': '武侠',
        'kkphim.category.khoa-hoc': '科学',
        'kkphim.category.than-thoai': '神话',
        'kkphim.category.chinh-kich': '正剧',
        'kkphim.category.kinh-dien': '经典',
        'kkphim.category.phim-ngan': '短片',
        'kkphim.country.trung-quoc': '中国',
        'kkphim.country.thai-lan': '泰国',
        'kkphim.country.hong-kong': '香港',
        'kkphim.country.phap': '法国',
        'kkphim.country.duc': '德国',
        'kkphim.country.ha-lan': '荷兰',
        'kkphim.country.mexico': '墨西哥',
        'kkphim.country.thuy-dien': '瑞典',
        'kkphim.country.philippines': '菲律宾',
        'kkphim.country.dan-mach': '丹麦',
        'kkphim.country.thuy-si': '瑞士',
        'kkphim.country.ukraina': '乌克兰',
        'kkphim.country.han-quoc': '韩国',
        'kkphim.country.au-my': '欧美',
        'kkphim.country.an-do': '印度',
        'kkphim.country.canada': '加拿大',
        'kkphim.country.tay-ban-nha': '西班牙',
        'kkphim.country.indonesia': '印尼',
        'kkphim.country.ba-lan': '波兰',
        'kkphim.country.malaysia': '马来西亚',
        'kkphim.country.bo-dao-nha': '葡萄牙',
        'kkphim.country.uae': '阿联酋',
        'kkphim.country.chau-phi': '非洲',
        'kkphim.country.a-rap-xe-ut': '沙特阿拉伯',
        'kkphim.country.nhat-ban': '日本',
        'kkphim.country.dai-loan': '台湾',
        'kkphim.country.anh': '英国',
        'kkphim.country.tho-nhi-ky': '土耳其',
        'kkphim.country.nga': '俄罗斯',
        'kkphim.country.uc': '澳大利亚',
        'kkphim.country.brazil': '巴西',
        'kkphim.country.y': '意大利',
        'kkphim.country.na-uy': '挪威',
        'kkphim.country.nam-phi': '南非',
        'kkphim.country.viet-nam': '越南',
        'kkphim.country.quoc-gia-khac': '其他',
        'filter.all': '全部',
        'search.filter.category': '类别',
        'search.filter.time': '时间',
        'search.filter.views': '观看次数',
        'search.filter.length': '时长',
        'filter.time.1w': '1周',
        'filter.time.2w': '2周',
        'filter.time.1m': '1个月',
        'filter.time.3m': '3个月',
        'filter.time.6m': '6个月',
        'filter.time.1y': '1年',
        'filter.views.1k': '> 1000',
        'filter.views.5k': '> 5000',
        'filter.views.10k': '> 10k',
        'filter.views.50k': '> 50k',
        'filter.views.100k': '> 100k',
        'filter.duration.5m': '> 5分钟',
        'filter.duration.10m': '> 10分钟',
        'filter.duration.30m': '> 30分钟',
        'filter.duration.60m': '> 60分钟',
        'thepy.category.china': '中国',
        'thepy.category.taiwan': '台湾',
        'thepy.category.japan': '日本',
        'thepy.category.eu': '欧美',
        'thepy.tab.recent': '最新',
        'thepy.tab.myfavs': '收藏',
        'thepy.tab.filters': '过滤'

    },
    ja: {
        'nav.home': 'ホーム',
        'nav.library': 'ライブラリ',
        'nav.search': '検索',
        'nav.downloads': 'ダウンロード',
        'nav.history': '履歴',
        'nav.settings': '設定',
        'nav.manga': 'マンガ',
        'nav.novel': '小説',
        'nav.movie': '映画',
        'settings.account': 'アカウント',
        'settings.logged_in': 'ログイン済み',
        'settings.edit_profile': 'プロフィール編集',
        'settings.appearance': '外観',
        'settings.theme': 'テーマ',
        'settings.theme.dark': 'ダーク',
        'settings.theme.light': 'ライト',
        'settings.accent_color': 'アクセントカラー',
        'settings.language': '言語',
        'settings.about': 'アプリについて',
        'settings.version': 'バージョン',
        'settings.logout': 'ログアウト',
        'settings.unlock.placeholder': 'パスコードを入力...',
        'settings.unlock.verify': '確認',
        'settings.unlock.success': 'ソースがロック解除されました！',
        'settings.unlock.fail': '無効なキーです',
        'search.placeholder': '漫画を検索...',
        'search.type_more': '3文字以上入力してください...',
        'search.no_results': '"{query}" の結果が見つかりません',
        'search.error': '検索エラー。',
        'search.genres': 'ジャンル',
        'search.nhentai.tags': 'タグ',
        'search.nhentai.artists': '作者',
        'search.nhentai.characters': 'キャラクター',
        'search.nhentai.parodies': 'パロディ',
        'search.nhentai.groups': 'グループ',
        'source.latest': '最新の更新',
        'source.popular': '人気',
        'source.popular_current': '現在',
        'source.popular_today': '今日',
        'source.popular_week': '今週',
        'source.popular_month': '今月',
        'source.popular_all': '全期間',
        'source.completed': '完結済',
        'source.unsupported': 'ソース「{source}」は現在サポートされていません。',
        'source.error': 'データの読み込みエラー。',
        'source.list_title': '{source} リスト',

        'profile.edit_title': 'プロフィールを編集',
        'profile.save': '保存',
        'profile.display_name': '表示名',
        'profile.bio': '自己紹介',
        'profile.bio_placeholder': '自己紹介を入力...',
        'profile.upload_success': '画像のアップロードに成功しました。',
        'profile.upload_failed': '画像のアップロードに失敗しました。',
        'profile.save_success': 'プロフィールが更新されました。',
        'profile.save_failed': 'プロフィールの保存に失敗しました。',
        'profile.crop_title': '画像の編集',
        'profile.crop_zoom_out': 'ズームアウト',
        'profile.crop_zoom_in': 'ズームイン',
        'profile.crop_done': '完了',
        'profile.no_frame': 'なし',
        'profile.no_cover': 'なし',

        'downloads.clear_all': 'すべてクリア',
        'downloads.pause_all': 'すべて一時停止',
        'downloads.resume': '再開 ({count})',
        'downloads.start': '開始 ({count})',
        'downloads.no_downloads': '待機中のダウンロードはありません。',
        'downloads.queue': 'キュー',
        'downloads.completed': '完了',
        'downloads.clear_history': '履歴を消去',

        // Comic Detail Modals
        'comic.filter': 'フィルター',
        'comic.sort': '並べ替え',
        'comic.display': '表示',
        'comic.filter.downloaded': 'ダウンロード済み',
        'comic.filter.unread': '未読',
        'comic.filter.bookmarked': 'ブックマーク済み',
        'comic.sort.source': 'ソース名 / アルファベット順',
        'comic.sort.chapter': 'チャプター番号順',
        'comic.sort.date': '更新日順 (API未対応)',
        'comic.display.source': 'ソースタイトル',
        'comic.display.chapter': 'チャプター番号',
        'comic.added_queue': 'すべてキューに追加しました',
        'comic.added_zip_queue': 'コミック全体(ZIP)をダウンロードキューに追加しました!',
        'comic.added_chapter': '第 {number} 話を追加しました',
        'comic.added_chapter_queue': '第 {number} 話をダウンロードキューに追加しました',
        'comic.no_chapters': 'チャプターがありません',
        'comic.queue_count': '{count} 話のダウンロードを予約しました',
        'comic.mark_read': '既読にする',
        'comic.mark_unread': '未読にする',
        'comic.mark_read_down': 'ここから下を既読に',
        'comic.bookmark': 'ブックマーク',
        'comic.add_queue': 'キューに追加',
        'comic.download_now': '今すぐダウンロード',

        'comic.chapters': 'チャプター',
        'comic.total': '全 {count} 話',
        'comic.download_all': '一括ダウンロード (ZIP)',
        'comic.queue_all': 'すべてキューに追加',
        'comic.read': '読む',
        'chapters.downloading': 'ダウンロード中...',
        'chapters.completed': '完了',
        'chapters.pending': '待機中',
        'chapters.paused': '一時停止',
        'chapters.failed': '失敗',

        // Reader Settings
        'reader.settings.mode': '読書モード',
        'reader.settings.general': '一般',
        'reader.settings.filters': 'カスタムフィルター',
        'reader.settings.reading_mode': '読書モード',
        'reader.mode.default': 'デフォルト',
        'reader.mode.paged': 'ページ送り（左から右）',
        'reader.mode.webtoon': '縦スクロール',
        'reader.settings.tap_zone': 'タップゾーン',
        'reader.tap.default': 'デフォルト',
        'reader.tap.l_shape': 'L字型',
        'reader.tap.kindle': 'Kindle風',
        'reader.tap.off': 'オフ',
        'reader.settings.invert_tap': 'タップゾーンを反転',
        'reader.invert.none': 'なし',
        'reader.invert.horizontal': '水平',
        'reader.invert.vertical': '垂直',
        'reader.invert.both': '両方',
        'reader.settings.side_padding': '横の余白',
        'reader.settings.auto_scroll': '自動スクロール速度',
        'reader.settings.auto_scroll_level': 'レベル {level}',
        'reader.settings.double_tap_zoom': 'ダブルタップでズーム',
        'reader.settings.bg_color': '背景色',
        'reader.bg.black': '黒',
        'reader.bg.gray': 'グレー',
        'reader.bg.white': '白',
        'reader.settings.show_page': 'ページ番号を表示',
        'reader.settings.fullscreen': '全画面表示',
        'reader.settings.custom_brightness': 'カスタム明るさ',
        'reader.settings.grayscale': 'グレースケール',
        'reader.settings.invert_colors': '色を反転',
        'reader.settings.crop_borders': '余白を切り取る',
        'reader.settings.split_double_pages': '見開きページを分割',

        // Misc
        'reader.chapter': '第 {number} 話',
        'comic.continue_reading': '続きを読む',
        'comic.start_reading': '読み始める',
        'comic.latest_chapter': '最新話',
        'comic.author': '作者',
        'comic.status': 'ステータス',
        'comic.status.ongoing': '連載中',
        'comic.status.completed': '完結済',

        // Home & Library
        'home.browse': 'ソースを閲覧',
        'home.latest': '最新',
        'home.coming_soon': '今後のアップデートで公開予定。',
        'library.title': 'ライブラリ',
        'library.empty': 'ライブラリは空です。',
        'library.browse': 'マンガを閲覧',
        'library.failed': 'ライブラリの読み込みに失敗しました.',

        //History
        'history.empty': 'まだ読んだことのない本はありません。',
        'history.failed': '読んだことのない本の読み込みに失敗しました。',
        'history.img_not_found': '画像が見つかりません。',
        'player.speed': '再生速度',
        'player.subtitles': '字幕',
        'player.episodes': 'エピソード',
        'player.next_episode': '次のエピソード',
        'player.skip_intro': 'イントロをスキップ',
        'player.now_playing': '再生中',
        'player.source_language': 'ソースとプロキシ',
        'kkphim.filter.release_year': 'リリース年',
        'kkphim.filter.all_years': 'すべての年',
        'kkphim.type.phimbo': 'ドラマ',
        'kkphim.type.phimle': '映画',

        'mtc.tabs.latest': '最新',
        'mtc.tabs.hot': 'ホット',
        'mtc.tabs.completed': '完結済',
        'mtc.tabs.curated': '厳選',
        'mtc.tabs.random': 'ランダム',
        'mtc.tabs.popular': '人気',
        'mtc.sort.viewday': '現在',
        'mtc.sort.viewweek': '今週',
        'mtc.sort.view': '全期間',
        'mtc.sort.like': 'いいね',
        'mtc.sort.following': 'フォロー',
        'mtc.sort.bookmarked': 'ブックマーク',
        'kkphim.filter.all': 'すべて',
        'kkphim.filter.all_genres': 'すべてのジャンル',
        'kkphim.filter.all_countries': 'すべての国',
        'kkphim.filter.type': 'タイプ',
        'kkphim.filter.sort': '並べ替え',
        'kkphim.filter.country': '国',
        'kkphim.type.series': 'ドラマ',
        'kkphim.type.single': '映画',
        'kkphim.type.hoathinh': 'アニメ',
        'kkphim.type.tvshows': 'テレビ番組',
        'kkphim.sort.update': '最近の更新',
        'kkphim.sort.year': 'リリース年',
        'kkphim.sort.new': '新着',
        'movie.watch_now': '今すぐ見る',
        'movie.watch_trailer': '予告編を見る',
        'movie.synopsis': 'あらすじ',
        'movie.episode_list': 'エピソードリスト',
        'kkphim.category.hanh-dong': 'アクション',
        'kkphim.category.co-trang': '時代劇',
        'kkphim.category.chien-tranh': '戦争',
        'kkphim.category.vien-tuong': 'SF',
        'kkphim.category.kinh-di': 'ホラー',
        'kkphim.category.tai-lieu': 'ドキュメンタリー',
        'kkphim.category.bi-an': 'ミステリー',
        'kkphim.category.phim-18': '18+',
        'kkphim.category.tinh-cam': 'ロマンス',
        'kkphim.category.tam-ly': 'ドラマ',
        'kkphim.category.the-thao': 'スポーツ',
        'kkphim.category.phieu-luu': 'アドベンチャー',
        'kkphim.category.am-nhac': '音楽',
        'kkphim.category.gia-dinh': 'ファミリー',
        'kkphim.category.hoc-duong': '学園',
        'kkphim.category.hai-huoc': 'コメディ',
        'kkphim.category.hinh-su': '犯罪',
        'kkphim.category.vo-thuat': '武術',
        'kkphim.category.khoa-hoc': '科学',
        'kkphim.category.than-thoai': '神話',
        'kkphim.category.chinh-kich': 'ドラマ',
        'kkphim.category.kinh-dien': 'クラシック',
        'kkphim.category.phim-ngan': 'ショートフィルム',
        'kkphim.country.trung-quoc': '中国',
        'kkphim.country.thai-lan': 'タイ',
        'kkphim.country.hong-kong': '香港',
        'kkphim.country.phap': 'フランス',
        'kkphim.country.duc': 'ドイツ',
        'kkphim.country.ha-lan': 'オランダ',
        'kkphim.country.mexico': 'メキシコ',
        'kkphim.country.thuy-dien': 'スウェーデン',
        'kkphim.country.philippines': 'フィリピン',
        'kkphim.country.dan-mach': 'デンマーク',
        'kkphim.country.thuy-si': 'スイス',
        'kkphim.country.ukraina': 'ウクライナ',
        'kkphim.country.han-quoc': '韓国',
        'kkphim.country.au-my': '欧米',
        'kkphim.country.an-do': 'インド',
        'kkphim.country.canada': 'カナダ',
        'kkphim.country.tay-ban-nha': 'スペイン',
        'kkphim.country.indonesia': 'インドネ西亚',
        'kkphim.country.ba-lan': 'ポーランド',
        'kkphim.country.malaysia': 'マレーシア',
        'kkphim.country.bo-dao-nha': 'ポルトガル',
        'kkphim.country.uae': 'UAE',
        'kkphim.country.chau-phi': 'アフリカ',
        'kkphim.country.a-rap-xe-ut': 'サウジアラビア',
        'kkphim.country.nhat-ban': '日本',
        'kkphim.country.dai-loan': '台湾',
        'kkphim.country.anh': 'イギリス',
        'kkphim.country.tho-nhi-ky': 'トルコ',
        'kkphim.country.nga': 'ロシア',
        'kkphim.country.uc': 'オーストラリア',
        'kkphim.country.brazil': 'ブラジル',
        'kkphim.country.y': 'イタリア',
        'kkphim.country.na-uy': 'ノルウェー',
        'kkphim.country.nam-phi': '南アフリカ',
        'kkphim.country.viet-nam': 'ベトナム',
        'kkphim.country.quoc-gia-khac': 'その他',
        'filter.all': 'すべて',
        'search.filter.category': 'カテゴリー',
        'search.filter.time': '時間',
        'search.filter.views': '視聴回数',
        'search.filter.length': '長さ',
        'filter.time.1w': '1週間',
        'filter.time.2w': '2週間',
        'filter.time.1m': '1ヶ月',
        'filter.time.3m': '3ヶ月',
        'filter.time.6m': '6ヶ月',
        'filter.time.1y': '1年',
        'filter.views.1k': '> 1000',
        'filter.views.5k': '> 5000',
        'filter.views.10k': '> 10k',
        'filter.views.50k': '> 50k',
        'filter.views.100k': '> 100k',
        'filter.duration.5m': '> 5分',
        'filter.duration.10m': '> 10分',
        'filter.duration.30m': '> 30分',
        'filter.duration.60m': '> 60分',
        'thepy.category.china': '中国',
        'thepy.category.taiwan': '台湾',
        'thepy.category.japan': '日本',
        'thepy.category.eu': '欧米',
        'thepy.tab.recent': '最新',
        'thepy.tab.myfavs': 'お気に入り',
        'thepy.tab.filters': 'フィルター'

    }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('vi'); // default vi as user requested initially
    const [theme, setTheme] = useState<Theme>('dark');
    const [accentColor, setAccentColor] = useState<AccentColor>('#f97316');

    useEffect(() => {
        try {
            const stored = localStorage.getItem(SETTINGS_STORAGE_KEY);
            if (stored) {
                const parsed = JSON.parse(stored);
                if (parsed.language) setLanguage(parsed.language);
                if (parsed.theme) setTheme(parsed.theme);
                if (parsed.accentColor) setAccentColor(parsed.accentColor);
            }
        } catch (e) {
            console.error('Failed to parse settings', e);
        }
    }, []);

    useEffect(() => {
        localStorage.setItem(SETTINGS_STORAGE_KEY, JSON.stringify({ language, theme, accentColor }));

        // Apply theme and accent color to document root
        const root = document.documentElement;

        // Apply accent color
        root.style.setProperty('--color-primary', accentColor);

        // Apply theme background and text colors
        if (theme === 'light') {
            root.style.setProperty('--color-bg', '#f5f5f5');
            root.style.setProperty('--color-surface', '#ffffff');
            root.style.setProperty('--color-surface-hover', '#e5e5e5');
            root.style.setProperty('--color-text', '#121212');
            root.style.setProperty('--color-text-muted', '#666666');
            root.style.setProperty('--color-border', '#d4d4d4');
            root.classList.remove('dark');
        } else {
            root.style.setProperty('--color-bg', '#121212');
            root.style.setProperty('--color-surface', '#1e1e1e');
            root.style.setProperty('--color-surface-hover', '#2c2c2c');
            root.style.setProperty('--color-text', '#e0e0e0');
            root.style.setProperty('--color-text-muted', '#9e9e9e');
            root.style.setProperty('--color-border', '#3c3c3c');
            root.classList.add('dark');
        }

    }, [language, theme, accentColor]);

    const t = (key: string, replacements?: Record<string, string | number>) => {
        let str = translations[language]?.[key] || translations['en']?.[key] || key;
        if (replacements) {
            Object.keys(replacements).forEach(k => {
                str = str.replace(`{${k}}`, String(replacements[k]));
            });
        }
        return str;
    };

    return (
        <SettingsContext.Provider value={{ language, setLanguage, theme, setTheme, accentColor, setAccentColor, t }}>
            {children}
        </SettingsContext.Provider>
    );
};

export const useSettings = () => {
    const context = useContext(SettingsContext);
    if (context === undefined) {
        throw new Error('useSettings must be used within a SettingsProvider');
    }
    return context;
};
